### PR TITLE
Fix new line after code block.

### PR DESCRIPTION
**Pull request by saiddjelmo**
Screenshot from 2021-09-16 12-03-10

### CODE REVIEW

**Comment by saiddjelmo** [comment]
When you typing ` ``` ` syntax for code block and next line is some text. It added new line after first later.

**Comment by cloverhearts** [comment]
Thank you for your PR :)
I'll check it soon

**Comment by cloverhearts** [comment]
Tested!
I think amazing improved to users via @saiddjelmo .
Thank you for your nice code again!


## Reproduce (problem)
problem

## Resolved (fixed)
fixed

**Comment by cloverhearts** [comment]
Ready for merge and deploy 1.1.6

**Pull request merged**
