### PR TITLE
+ Remove core-js and regenerator

### LINKED ISSUE #64: ERROR on iOS device: Unhandle promise rejection: null is not a funtion
When open the webpage on browser of an iOS device, it gets stuck and user can't interact with.

https://user-images.githubusercontent.com/7076329/176960294-8b6b6728-c43d-4fa4-9043-abdcc5dd9a7c.mp4

Here the iOS Chrome inspector error:
WhatsApp Image 2022-07-01 at 1 45 37 PM

The error is shown when the app loads. 

Without **quilljs-markdown** installed everything works fine.

In Android or desktop devices it works fine.

Angular 7
Quill 1.3.7
NgxQuill 7.3.1

### LINKED ISSUE #65: not compatible with SSR
I use quill in a universal Angular app, and want to render the form in server-side

this line `Quill.register({ 'modules/QuillMarkdown': QuillMarkdown }, true);` causes the error `Uncaught (in promise): ReferenceError: document is not defined`

### PR DESCRIPTION
**Pull request by cloverhearts**
Fixed #64  #65 

Remove to core-js and regenerator-runtime on dependencies.
because quilljs-markdown has two problems.
first. cannot support SSR BUILD with core-js.
- in core-js, Exists with document element. but cannot build with using document element on SSR Build.
second, regenerator-runtime module does not support some ios mobile safari.

so, i was decide removed module.

### CODE REVIEW

**Comment by cloverhearts** [comment]
@zmaximo1990 @eng-dibo

Could you check on this pr?

`npm install --save cloverhearts/quilljs-markdown#pull/66/head`

**Comment by cloverhearts** [comment]
I will merge at tomorrow and deploy to 1.2.0

**Comment by cloverhearts** [comment]
merge

**Comment by its-dibo** [comment]
> @cloverhearts It works 🤓👏!
> 
> WhatsApp Image 2022-07-19 at 11 35 43 AM
> 
> Thanks you!.
> 
> We will waiting for the next release.
> 
> Best.

nice <3

**Comment by cloverhearts** [comment]
has been released. :)
Thank you

**Pull request merged**
