### PR TITLE
Support Markdown render when pasting markdown context

### LINKED ISSUE #23: Support Pasting
If I paste a block of Markdown it does not automatically format it at all.

### PR DESCRIPTION
**Pull request by cloverhearts**
fixed #23 

markdown-render-feature-inprogress01

- [x] Version up 1.1.0
- [x] Added basic render logic.
- [x] Adjust action for markdown redner
- [x] Header render
- [x] Add doc
- [x] invalid render for code block
- [x] invalid render for checkbox
- [x] number/bullet list
- [x] Block quote
- [x] Link

Test markdown
```markdown

# Hello markdown
# SAMSAM

1. original
2. second

   He said **strong** and `hightlight`

``
Hello world code block
``


1. hello world

Many syntax  ~~italics~~

[] nick checkbox
[x] eeeee



```

### CODE REVIEW

**Comment by darkfrog26** [comment]
Impressively fast response time. :) Any idea when you think this will be finished?

**Comment by cloverhearts** [comment]
probably... 1 week? 2 weeks?

**Comment by cloverhearts** [comment]
It is not possible to accurately predict the completion date.
But I will try to my goal until 2 weeks.

**Comment by cloverhearts** [comment]
list

list done

**Comment by cloverhearts** [comment]
image

And bullet

**Comment by cloverhearts** [comment]
checkbox

Added support for checkbox

**Comment by cloverhearts** [comment]
pasting

Added Support for code block
and bug fix another side.



Test markdown
```
# Hello markdown
# SAMSAM

1. original
2. second

   He said **strong** and `hightlight`

`` `

Hello world

1. hello world

Many syntax  ~~italics~~

[ ] nick checkbox
[x] eeeee


`` `


1. hello world

Many syntax  ~~italics~~

[] nick checkbox
[x] eeeee

[ ] white space checkbox



```

**Comment by cloverhearts** [comment]
Problems 2 case.

> This is a block quote.

This is a [Link](https://link) and `inline code`

**Comment by cloverhearts** [comment]
render-repeat

Fixed inline and link, block quote

**Comment by cloverhearts** [comment]
Read for merge

**Comment by cloverhearts** [comment]
@darkfrog26 
Could you please test for this pr?

You can test with npm about this.
```
npm install https://github.com/cloverhearts/quilljs-markdown.git#feature/issue-23 --save
```

**Comment by darkfrog26** [comment]
@cloverhearts yes, I'll try to get it tested today.

**Comment by darkfrog26** [comment]
Not sure why, but it doesn't seem to be working right for me. Not only does the paste not seem to work, but something seems to happen where it stops processing markdown at all even as I type. I'm not seeing any errors in the JS console, but something is breaking internally. I need to set up a repeatable environment so I can share it back with you as I only tested it in my app thus far. I do have the mentions module loaded as well, but I'm not sure if that's impacting it.

**Comment by darkfrog26** [comment]
Oops, my bad, the problem was that I was pasting with formatting. Pasting with CTRL + SHIFT + V made it better, but trying with this snippet:
```
## 0.13.0 - December 11, 2020
- Features
  - Improvements to unread status functionality
  - Improved how internal links appear and work in the application
  - Updates to www.courio.com landing page
- Bug Fixes
  - Fixes to file attachment bugs
  - Fixed regression bug with "Offline" status in higher latency devices
```
The list formatting is very wrong

**Comment by cloverhearts** [comment]
@darkfrog26 Thank you for your report.
I'll re-fix again.

**Comment by cloverhearts** [comment]
listup

Resolved for depth of list

@darkfrog26 
Could you test again?

**Comment by darkfrog26** [comment]
@cloverhearts it appears to be working now for that snippet, but trying one with a code block in a list item:
```
## 0.6.13 - December 14, 2019
- Features
    - Added filtering support to sidebar
    - Added hierarchical structure of content
    - Updated streams in sidebar to be sorted by most recent message received
    - Added showing distinct color on left of messages when multiple streams are being viewed
    - Added default icon to streams in sidebar
    - Support for unread status on streams
    - Updated push notifications to go back to only sending if no focused/active connections are present
- Bug Fixes
    - Better detection of `offline` and `online` status for maintaining connectivity
    - Resolved issue with instant notifications
```

It seems to ignore the back-ticks

**Comment by cloverhearts** [comment]
improved for render logic about safety

safety

@darkfrog26 
Resolved
I hope this is the last test :)

**Comment by darkfrog26** [comment]
Looks good to me! :)

**Comment by cloverhearts** [comment]
@darkfrog26 
Thank you for your big help.
I'll publish to 1.1.0 version for quilljs-markdown in at UTC 10:00

Thank you again

**Comment by cloverhearts** [comment]
Merge

**Pull request merged**
