### PR TITLE
Add destroy() method to disable markdown support on-the-fly

### LINKED ISSUE #50: Disable markdown on-the-fly
Hi, I'd like to give my users the ability to enable/disable markdown support on-the-fly. 

When markdown is enabled, I just call `new QuillMarkdown(quill)`, which works fine.

But I haven't found a way to disable it on the fly. `delete`ing the `QuillMarkdown` instance doesn't seem to work. We'd probably have to remove the event listeners added in the constructor.

Is there any support for that? Thanks!

### PR DESCRIPTION
**Pull request by jfhr**
This would close #50 

Thanks for the good work @cloverhearts !

### CODE REVIEW

**Comment by cloverhearts** [comment]
Thank yo for your nice PR
I'll check it soon!

**Comment by cloverhearts** [comment]
I was finished test this feature.
Does well work!

and can you one more help?
We need a document about this feature in my opinion.
(i am think small description is enough) 

If write description on this pr comment, i will add to document with another PR.

THANK YOU SO MUCH!

**Comment by jfhr** [comment]
Hi, I'd suggest the following description:

## destroy

Call `destroy()` to remove the event listener and disable markdown support:

```js
const quillMarkdown = new QuillMarkdown(editor, markdownOptions)
// markdown is enabled

quillMarkdown.destroy()
// markdown is now disabled
```

To re-enable support, create a new instance.

**Comment by cloverhearts** [comment]
Thank you :)
I'll merge to master at tomorrow.

**Comment by cloverhearts** [comment]
Merge

**Pull request merged**
